### ISSUE TITLE
How to add a json file to set the port?

### ISSUE THREAD

**Issue by TencentSZ** [tonysneed/Demo.DotNetSelfHost#11]
Would you like to further guide me to config this self-hosting web server?  I want to use a port other than 5000, and it would be better if the app load port setting from a json file.

**Comment by tonysneed** [comment]
There are a number of ways to do this. See https://andrewlock.net/5-ways-to-set-the-urls-for-an-aspnetcore-app/

**Comment by TencentSZ** [comment]
> 
> 
> There are a number of ways to do this. See https://andrewlock.net/5-ways-to-set-the-urls-for-an-aspnetcore-app/

But launchSettings.json seems not to be included in 'publish' or 'release' folder. That means end users cannot change the port after I distribute my program to them. Am I right?

**Comment by TencentSZ** [comment]
After I created a settings.json file, I managed to load config from it.

`        
public static IHostBuilder CreateHostBuilder()
        {
            var configuration = new ConfigurationBuilder().SetBasePath(Environment.CurrentDirectory)
                                          .AddJsonFile("settings.json")
                                          .Build();
            return Host.CreateDefaultBuilder()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseConfiguration(configuration).UseStartup<Startup>();
                });
        }
`
of couse `UseUrls` is OK too.
