### ISSUE TITLE
Is the Demo.DotNetSelfHost (Winform and WebApi) running in one process ?

### ISSUE THREAD

**Issue by rekonin332** [tonysneed/Demo.DotNetSelfHost#14]

**Comment by rekonin332** [comment]
Can anyone give a hint? Thanks a lot

**Comment by tonysneed** [comment]
@rekonin332 Thanks for your question. The answer is YES. The WinForm app hosts the process, and Kestrel runs in-process. So it is just **one process** for the WinForm app that includes a Web API. See this [SO answer](https://stackoverflow.com/a/61608221).

**Comment by tonysneed** [comment]
Feel free to re-open if there are further questions.

**Comment by tonysneed** [comment]
Closing as answered.
