### ISSUE TITLE
Run x64 version of App

### ISSUE THREAD

**Issue by declspec-cdecl** [tonysneed/Demo.DotNetSelfHost#2]
How to use asp core in x64 version of program?

**Comment by tonysneed** [comment]
I just asked David Fowler the question [here](https://github.com/davidfowl/AspNetCoreCsproj/issues/2#issuecomment-264280870).

**Comment by tonysneed** [comment]
This is a hack that will go away with the new CSPROJ format. See David's [answer](https://github.com/davidfowl/AspNetCoreCsproj/issues/2#issuecomment-264394896).
