### ISSUE TITLE
Error: "The type or namespace name "AspNetCore" does not exist in the namespace "Microsoft" (perhaps there is no link to the assembly)"

### ISSUE THREAD

**Issue by it19862** [tonysneed/Demo.DotNetSelfHost#4]
VS -2017
How to fix the error?

The type or namespace name "AspNetCore" does not exist in the namespace "Microsoft" (perhaps there is no link to the assembly)
Could not find the type or name of the namespace "RouteAttribute" (it may be that there is no using directive or assembly reference).
-- // --- // --- // ---// ---// ---// --- // ---  "Route"     -- // --- // --- // ---// ---// ---// --- // ---
-- // --- // --- // ---// ---// ---// --- // ---  "HttpGetAttribute" -- // --- // --- // ---// ---// ---// --- // ---
-- // --- // --- // ---// ---// ---// --- // ---  "HttpGet" -- // --- // --- // ---// ---// ---// --- // ---
-- // --- // --- // ---// ---// ---// --- // ---  "IActionResult" -- // --- // --- // ---// ---// ---// --- // ---
-- // --- // --- // ---// ---// ---// --- // ---  "HttpPostAttribute" -- // --- // --- // ---// ---// ---// --- // ---
-- // --- // --- // ---// ---// ---// --- // ---  "HttpPost" -- // --- // --- // ---// ---// ---// --- // ---
-- // --- // --- // ---// ---// ---// --- // ---  "IActionResult" -- // --- // --- // ---// ---// ---// --- // ---
-- // --- // --- // ---// ---// ---// --- // ---  "FromBodyAttribute" -- // --- // --- // ---// ---// ---// --- // ---
-- // --- // --- // ---// ---// ---// --- // ---  "FromBody" -- // --- // --- // ---// ---// ---// --- // ---
-- // --- // --- // ---// ---// ---// --- // ---  "JsonResult" -- // --- // --- // ---// ---// ---// --- // ---
-- // --- // --- // ---// ---// ---// --- // ---  "NoContentResult" -- // --- // --- // ---// ---// ---// --- // ---

And so on

**Nuget error**
[AspNetCI] Failed to load service index for source https://www.myget.org/F/aspnetcirelease/api/v3/index.json.
  The response status code does not indicate successful completion: 404 (Feed does not exist.).
[AspNetCI] Failed to load service index for source https://www.myget.org/F/aspnetcirelease/api/v3/index.json.
  The response status code does not indicate successful completion: 404 (Feed does not exist.).
[AspNetCI] Failed to load service index for source https://www.myget.org/F/aspnetcirelease/api/v3/index.json.
  The response status code does not indicate successful completion: 404 (Feed does not exist.).
[AspNetCI] Failed to load service index for source https://www.myget.org/F/aspnetcirelease/api/v3/index.json.
  The response status code does not indicate successful completion: 404 (Feed does not exist.).
[AspNetCI] Failed to load service index for source https://www.myget.org/F/aspnetcirelease/api/v3/index.json.
  The response status code does not indicate successful completion: 404 (Feed does not exist.).
[AspNetCI] Failed to load service index for source https://www.myget.org/F/aspnetcirelease/api/v3/index.json.
  The response status code does not indicate successful completion: 404 (Feed does not exist.).
[AspNetCI] Failed to load service index for source https://www.myget.org/F/aspnetcirelease/api/v3/index.json.
  The response status code does not indicate successful completion: 404 (Feed does not exist.).

![2019-07-04_23-53-19](https://user-images.githubusercontent.com/18245828/60687525-b71f5b00-9eb7-11e9-86b9-823f521fa845.png)
![2019-07-04_23-54-03](https://user-images.githubusercontent.com/18245828/60687535-bd153c00-9eb7-11e9-93ac-16ca12b065ef.png)
![2019-07-04_23-58-47](https://user-images.githubusercontent.com/18245828/60687539-c1415980-9eb7-11e9-946a-168da4360a4c.png)

**Comment by tonysneed** [comment]
Thanks for the issue ... this repo is based on the old project.json format, which has been deprecated.  It will need to be updated to .NET Core 2.x. Would you care to submit a PR? If not, I’ll see if I can have a crack at it.

**Comment by it19862** [comment]
@tonysneed 

Thanks for the answer.
I do not understand English well.

Could you clarify what is required of me?

**Comment by tonysneed** [comment]
I think it will be easier for me to update the repo to the latest version of .NET Core. I'll create a pull request sometime today.

**Comment by tonysneed** [comment]
Updated all the code via #5. It all works now with .NET Core 2.2. Enjoy!
