### ISSUE TITLE
What is the "name" field for?

### ISSUE THREAD

**Issue by it19862** [tonysneed/Demo.DotNetSelfHost#7]
What is the "name" field for?
![2019-07-14_00-24-49](https://user-images.githubusercontent.com/18245828/61176696-0a875c80-a5ce-11e9-90b2-c613dc66f32a.png)

**Comment by tonysneed** [comment]
Yes, issuing an HTTP Post to the service populates the Name textbox, and issuing a Get will return whatever text has been entered into the Name textbox.
