### ISSUE TITLE
The program dose not respond to http request after upgrading all packages to latest version.

### ISSUE THREAD

**Issue by TencentSZ** [tonysneed/Demo.DotNetSelfHost#9]
I followed the instruction to apply a self-hosting server to my project. Besides, I upgraded all packages to the latest versions by nuget. After that, I ran debugging only to find it did not respond to any http request, although the compile procedure did not raise any failure.

**Comment by tonysneed** [comment]
I tried this also, and I was unable to get it to work after upgrading the packages. I will post an answer here as soon as I find it.

**Comment by tonysneed** [comment]
I got this to work by creating a .NET 5 Windows Forms app and changing the Project SDK to `Microsoft.NET.Sdk.Web`.

**Comment by TencentSZ** [comment]
I'm glad you find a way to solve this, but would you mind keeping the old solution in another repo directory? I come to this idea because .Net 5.0 runtime is not installed in many computers so developers may be reluctant to change their projects to .Net 5.0.

**Comment by tonysneed** [comment]
Is .NET Core 3.1 acceptable? If so, the same solution should apply. I can create a branch for it.

**Comment by tonysneed** [comment]
Here is the .NET Core 3.1 branch: https://github.com/tonysneed/Demo.DotNetSelfHost/tree/dotnet-3-1. Please let me know if I can be of further assistance.
